[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/Adafruit BMP280 Library @ ^2.6.8

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/Adafruit BMP280 Library @ ^2.6.8
